# Dependencies
markdown: kramdown

# Custom vars
project_name: scratchie.js
current_version: 0.0.0
repository_url: https://github.com/andreruffert/scratchie.js

exclude:
- "Gemfile"
- "README.md"

sass:
    style: :compressed
